blank_issues_enabled: true
contact_links:
  - name: ğŸ“– ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ
    url: https://github.com/darui3018823/privacy_shield/blob/main/Readme.md
    about: READMEã§ä½¿ã„æ–¹ã‚’ç¢ºèªã§ãã¾ã™
  - name: ğŸ’¬ Discussions
    url: https://github.com/darui3018823/privacy_shield/discussions
    about: ä¸€èˆ¬çš„ãªè³ªå•ã‚„è­°è«–ã¯Discussionsã‚’ã”åˆ©ç”¨ãã ã•ã„
